### ISSUE TITLE
Error fetching image

### ISSUE THREAD

**Issue by lijxse** [DWilliames/google-sheets-sync-figma#1]
Thank you for making this plugin, I really like it.
After this update, I found a lot of "Error fetching imge" when filling images, it's red, I've hardly seen this kind of prompt before.

Whether I use my own image bed or Google Drive, it's always red.

**The image bed I use is:**
postimg.cc

**I have some test images that I use for you to test:**

https://i.postimg.cc/YqTTBLsJ/girl-1.jpg
https://i.postimg.cc/m216j2gV/girl-10.jpg
https://i.postimg.cc/zGKzsr0F/girl-100.jpg
https://i.postimg.cc/TPcRPc8y/girl-101.jpg
https://i.postimg.cc/c1bbf80r/girl-11.jpg
https://i.postimg.cc/Ls2CmtB0/girl-12.jpg
https://i.postimg.cc/bJvmtq5x/girl-13.jpg
https://i.postimg.cc/SstDLw0w/girl-14.jpg
https://i.postimg.cc/mgQpxXMH/girl-15.jpg
https://i.postimg.cc/zvbpx083/girl-16.jpg
https://i.postimg.cc/jjc82DMq/girl-17.jpg
https://i.postimg.cc/WpxPTyDW/girl-18.jpg
https://i.postimg.cc/bNbfJRkz/girl-19.jpg
https://i.postimg.cc/DwsHvyVm/girl-2.jpg
https://i.postimg.cc/5yhgTL2g/girl-20.jpg
https://i.postimg.cc/hG2HwZW0/girl-21.jpg
https://i.postimg.cc/nz5NVsLj/girl-22.jpg
https://i.postimg.cc/7P5kv4LJ/girl-23.jpg
https://i.postimg.cc/Bn0911B2/girl-24.jpg
https://i.postimg.cc/0y0gG2VF/girl-25.jpg
https://i.postimg.cc/KYG60SVz/girl-26.jpg

**Comment by DWilliames** [comment]
Thanks @lijxse — I'm looking into this one now. 
It's quite bizarre. It seems like all those images are of type `image/jpeg` — however consistently some specific ones are returning errors. 

I'll keep diving into it to try and find a fix; thanks for your patience.
![image](https://user-images.githubusercontent.com/6570446/104240596-6e832d80-54b0-11eb-8aff-59f52a4d3204.png)

**Comment by DWilliames** [comment]
Okay I think I solved it now and have published a Plugin update.
Are you able to check now for me and see if the new version fixes it for you.

**Comment by lijxse** [comment]
Wow, I didn't expect it to be fixed so quickly, thanks a lot. 
After my test, most of them are working, but some of them are still wrong, my test is "avatar_cn" is wrong.

#### I used the video to record the error I encountered:
https://drive.google.com/file/d/18GPQdlO42-nkcOpgmNeSog4mTFy58ela/view?usp=sharing

#### Here are my Google Sheets:
https://docs.google.com/spreadsheets/d/1t23BAon8spOILyH49A_htAPDAJ03Hfw5ZUgiqHdOkU0/edit?usp=sharing

**Comment by DWilliames** [comment]
Thanks for sending through that recording and a link to your sheet; it's super helpful. I'm looking into it again now.
It is quite weird that there's only a few that don't seem to load correctly.

**Comment by lijxse** [comment]
Yeah, I'm not sure if there's a problem with the image itself, I've uploaded a local image package here, hopefully that will help you.
[1、亚洲.zip](https://github.com/DWilliames/google-sheets-sync-figma/files/5803261/1.zip)

**Comment by DWilliames** [comment]
Yeah I think it may be an issue with the hosting service 🤷‍♂️ Or potentially a bug with Figma itself.
Either way, I found a sneaky work around. Which seems to work for around 100 images on a Figma page, which I just published.
But if you need to load lots more than that at once, it may still run into some issues.

In the meantime — after spending a lot of time trying to fix this; I don't think there's anything else I can do apart from the work around I just published. So I'll close off this issue.

I'll reopen it in the future if I can any progress at a future date.

**Comment by lijxse** [comment]
It doesn't affect normal use anymore, Google Sheets For Figma is a plugin I use every day, thank you very much for making it.

**Comment by KovalevichD** [comment]
@DWilliames Hey, David! I have the same issue with fetching images from Google Drive. I've inspected the request and it has the 403 status. Google blocks sending automatic requests (reCAPTCHA). Maybe this information will be useful.

[Link](https://support.google.com/websearch/answer/86640)
![image](https://user-images.githubusercontent.com/53308771/147245436-331ecb5d-d28b-4698-a98f-f469b4f06171.png)

**Comment by newoldschool** [comment]
Hi! there is any news about this, any chance we can get this fixed? I really love your plugin too, I don't use it every day but is very useful, but I always have several errors that I have to manually put the image.

Thanks!

**Comment by zharmakin** [comment]
looks like Figma has problems fetching images from Google Sheets plugin as well as other JSON -> Content plugins.

**Comment by vitalkac** [comment]
I have the same issue... It is still not solved. It works a few times, then it is not working for a day or few. Every time it is different. I love the plugin though, but with these issues it is easier to do it manually...

**Comment by GiulianoHS** [comment]
@DWilliames Hi thank you for creating this plugin. I'm getting a 403 error when I try to fetch images from the spreadsheet with your plugin. Is this something that is already fixed? 

I've given full acces with a link so it should work?

**Comment by Banksy465** [comment]
Same here, love the plugin. I'm not very technical, but I was able to fix my issue by putting the images folder on the same level as the profile cards in google drive. Can't really back it up with technical evidence, but it seemed to work.

**Comment by carambamoreno** [comment]
Hello.

I've been using this for some time now. It seems to be related to a limit to the number of syncs you can perform in a period of time. All information is synced every time but images start being blocked from the third time on and showing the 403 error.

If I wait a couple of hours, I can continue syncing the rest. 

I am syncing image URLs from different google sheets. The group of images varies from 5 to 40+ images at a time. I sync sheet by sheet. Almost all images are hosted on google drive.

**Comment by RobH22** [comment]
I tried Dropbox, my own website and OneDrive. All of them give 'Error fetching image." I had hopes that at lease one of those repositories would work. If I grab an image addresss, say from Amazon, it works perfectly. But, even with the permissions in all of my online sites set to be as wide open as possible, not go.

**Comment by subgeta** [comment]
Hello, Dave, first and foremost, thanks for the awesome plug-in! Keep up the good work.
I just wanted to chime in as I've come across this issue myself and I may seem to have solved this error.
It looks like you need the actual address of the image that you are trying to reach. Google drive share link is an embedded image viewer from the looks of it. So you need the actual image link to fetch the image in the plug in.

Steps: (on Firefox)
1. When you open your google drive, click on the image and view it.
2. Press CTRL+SHIFT+I keys to open the web Inspector.
3. Select and highlight the image.
4. On the web code that's highlighted, you will see the images "true" web address.
5. Copy it and add it to your Google sheet.
![Screenshot 2024-10-12 135755](https://github.com/user-attachments/assets/76b8bf8a-0ea9-4fb4-b127-c9b57913a525)

**Comment by alvathoni** [comment]
Hello, please help. I experienced same issue, I've changed the google drive link to direct link like this (https://drive.google.com/uc?id=1BciBrUf3JYZ0qckmPC8zwGARP1tyleYg)  but it's still shown error fetching images. Is there any solution? Thank you

<img width="846" alt="Image" src="https://github.com/user-attachments/assets/533debd8-334d-4d14-9a2f-72978982195c" />

**Comment by lijxse** [comment]
> Hello, please help. I experienced same issue, I've changed the google drive link to direct link like this (https://drive.google.com/uc?id=1BciBrUf3JYZ0qckmPC8zwGARP1tyleYg) but it's still shown error fetching images. Is there any solution? Thank you
> 
> <img alt="Image" width="846" src="https://private-user-images.githubusercontent.com/58716140/456426786-533debd8-334d-4d14-9a2f-72978982195c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAyNDM4MTMsIm5iZiI6MTc1MDI0MzUxMywicGF0aCI6Ii81ODcxNjE0MC80NTY0MjY3ODYtNTMzZGViZDgtMzM0ZC00ZDE0LTlhMmYtNzI5Nzg5ODIxOTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjE4VDEwNDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYzFkMWRkN2RjNGQyYTVjZTZmYjFkOWY2ZjJiYTcwMTVhNDhiNWUyMGIwNWQ1OTI4ZDZmMGNjZThkMTJkNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3fQlZ2HZYNM5uqW2efgSLwUquFANEoGMvUG0lIThdoM">

Maybe you can try switching to another image hosting service. Usually, it's either a problem with the image hosting service or a network issue.

**Comment by fiasos** [comment]
> Hello, Dave, first and foremost, thanks for the awesome plug-in! Keep up the good work. I just wanted to chime in as I've come across this issue myself and I may seem to have solved this error. It looks like you need the actual address of the image that you are trying to reach. Google drive share link is an embedded image viewer from the looks of it. So you need the actual image link to fetch the image in the plug in.
> 
> Steps: (on Firefox)
> 
> 1. When you open your google drive, click on the image and view it.
> 2. Press CTRL+SHIFT+I keys to open the web Inspector.
> 3. Select and highlight the image.
> 4. On the web code that's highlighted, you will see the images "true" web address.
> 5. Copy it and add it to your Google sheet.
>    ![Screenshot 2024-10-12 135755](https://github.com/user-attachments/assets/76b8bf8a-0ea9-4fb4-b127-c9b57913a525)


it works, even from chrome
the problem is that the links have to be taken one by one manually. have you found any solutions?

**Comment by subgeta** [comment]
> it works, even from chrome the problem is that the links have to be taken one by one manually. have you found any solutions?

The only solution to this, if using google drive, is to do it manually.
This first and foremost seems it is due to file hosts link url address. 
You need a direct non-intrusive link to your image. (think of it like a clean link with no embedded HTML, or other coding.)
Also you will need to make sure to link it correctly in your google sheet doc, try to avoid long names, weird characters, spaces etcs.
Keep the images optimized as well, large images both in memory and size can potentially cause loading issues.
