### ISSUE TITLE
Error: in resize: Expected "height" to have value >= 0.01

### ISSUE THREAD

**Issue by MarkThomasJohnson** [DWilliames/google-sheets-sync-figma#10]
**Describe the bug**
tl;dr: Negative value in height doesn't work.

**To Reproduce**
Give height a negative value (you can't do this for somewhat obvious reasons)

**Expected behavior**
Potentially to maintain height, but as positive value anyway

**Additional context**
I'm doing some abstract calculations to determine height in the a weird way to make line graphs. I'm able to put these together to rig something together that probably should not come together. I should probably just change the math in my google sheet rather than logging this, but I'm logging it just here just to log it.

**Comment by DWilliames** [comment]
Should be fixed in the latest release I just pushed :)
