### ISSUE TITLE
Fill colour #ABC → would set the fill to #AABBCC,Although this is not a bug, it is a bad logic.

### ISSUE THREAD

**Issue by mswbol** [DWilliames/google-sheets-sync-figma#20]
Fill colour #ABC → would set the fill to #AABBCC,Although this is not a bug, it is a bad logic.

e.g
#AB → would set the fill to #ABABAB
#A → would set the fill to #AAAAAA

Therefore, #ABC → would set the fill to #AABBCC is right.

#~ABC → would set the fill to #AABBCC.

**Comment by hanajoruno** [comment]
> Fill colour #ABC → would set the fill to #AABBCC,Although this is not a bug, it is a bad logic.
> 
> e.g
> #AB → would set the fill to #ABABAB
> #A → would set the fill to #AAAAAA
> 
> Therefore, #ABC → would set the fill to #AABBCC is right.
> 
> #~ABC → would set the fill to #AABBCC.

我英语不好，您可否翻译成中文让我看一下。

**Comment by mswbol** [comment]
好吧，我尝试了在Figma 输入ABC 会自动转换成AABBCC，这款插件的代码应该是遵循这个规则的。
