### ISSUE TITLE
Invisible text?

### ISSUE THREAD

**Issue by kgronecitefull** [DWilliames/google-sheets-sync-figma#22]
Link to doc in question: https://docs.google.com/spreadsheets/d/1h-l12zpb-E7Y0kWhTRxOqZ-T5cQg2PZStzBu0NCFx38/edit?usp=sharing

**Describe the bug**
When “re-syncing” Google Sheets Data, all text fields (there are a few hundred in the entire document) get set to invisible. I am able to ctrl/z to undo the change or have to manually go in and set all appropriate fields to visible. Happens repeatedly.

**To Reproduce**
See screenshots attached below.

**Expected behavior**
I expect the data to update without making the text fields invisible. (maybe I broke something myself? idk?)

**Additional context**
Was working perfectly until about 4 pm yesterday (Arizona, USA) (16 hours ago)

.....
![image](https://user-images.githubusercontent.com/62361053/110810094-b1f4e080-8242-11eb-94f4-41954bc342cc.png)
![image](https://user-images.githubusercontent.com/62361053/110810123-b8835800-8242-11eb-9335-35d5eca46701.png)

**Comment by dpolyakov** [comment]
i have same issue

**Comment by kgronecitefull** [comment]
I think I found a fix, I had column A as an organizer column that wasn't being used in the sync, somehow it was affecting the display. When I removed the column entirely, things seemed to go back to normal...
