### ISSUE TITLE
Font Styles

### ISSUE THREAD

**Issue by michellenmiles** [DWilliames/google-sheets-sync-figma#43]
Is there a way to apply font styles (color, size, etc) to individual words within a paragraph or sentence of text? And if so, is there a way to bold or italicize text? If not, I think that would be super useful!

**Comment by prakashkarkee** [comment]
According to [documentation]( https://docs.sheetssync.app/special-data-types ) by DWilliames David Williames, 
> Google Sheets Sync has the ability to change properties on the layer (e.g Fill colour, Font size etc.) – by setting the Value in your Sheet in a specific way. You can even chain multiple together.

As it say , it applied to layer (Text layer ) so whole text content's properties on text layer will be affected.This means individual word or sentence of paragraph on the text layer can't have unique text style. But if you insist and you want it on **Google sheets Sync**  then you can request feature to plugin owner @DWilliames with your ideology and suggestion. Beside that Figma has rich in this resource called `Team LIbrary`. It has quote that i like  

> Don’t reinvent the wheel with every design.

Figma support **Text style** and **color style** as `Asset Team Library` so you can apply custom **text style** (font , size, bold/italicize, line height, camel-case, etc) across all the figma file. Individual word or sentence within paragraph can be made unique text style and colorful. For immediate, use shortcut while typing Ctrl+B for **bold** and Ctrl+I for **italicize** character and to disable press twice. Need more font styles then create **Text style** and **Color style** from below tutorial figma link. 
Tutorial Figma link:  https://www.figma.com/file/jFYLsqd1P7xHURCGfuP2iG/?node-id=0%3A1 
My Example Figma link : https://www.figma.com/file/BlYa337WmX6JZDIHwa9uTB/Untitled-Copy?node-id=103%3A74

Illustration Screenshot : 
![Single Paragraph](https://user-images.githubusercontent.com/15900029/120619693-f24baf80-c47b-11eb-988f-f905379d0716.png)

I hope this can be helpful, let me know.

**Comment by michellenmiles** [comment]
Thank you so much for this info! :)
