### ISSUE TITLE
Error: in set_fills: Expected "fills.[0].color.r" to have type number but got NaN instead

### ISSUE THREAD

**Issue by codyzzd** [DWilliames/google-sheets-sync-figma#6]
**Describe the bug**
submit to update when show the screen with warning
Error: in set_fills: Expected "fills.[0].color.r" to have type number but got NaN instead

**To Reproduce**
just use like normal

**Expected behavior**
window close and the fields updated

**Comment by DWilliames** [comment]
Thanks for this @codyzzd.
I just pushed an updated to the plugin which should fix this. If you still encounter the issue, then please re-open this issue.

Cheers
