### ISSUE TITLE
Error: in set_y: Expected "y" to have type number but got NaN instead

### ISSUE THREAD

**Issue by kgronecitefull** [DWilliames/google-sheets-sync-figma#7]
**Describe the bug**
I am producing various card (news stories that fit within a defined structure (but there are different cards for different instances), the second set of cards triggers the error. 

This is a great plugin by the way. I love it.

**Comment by DWilliames** [comment]
Thanks for this @kgronecitefull.
I just pushed a plugin which should fix this. If you still encounter the issue, then please re-open this issue.

Cheers

**Comment by kgronecitefull** [comment]
Thanks David. I found a little work around and it seems to be working great.

I can't tell you how valuable this is to me.

Where can I leave you you glowing review or 5?

-Kyle Grone
CEO, Co-Founder
Citefull.com
602.544.6125

(Sent from mobile,  please excuse any typos)

**Comment by DWilliames** [comment]
Thanks @kgronecitefull — that's amazing to hear how valuable it is :) 
If you want to support the development of it (no pressure at all); I just set up a page at: [buymeacoffee.com/davew](https://buymeacoffee.com/davew) where you could shout me a coffee. 
Every little bit is super appreciated 🙌

**Comment by kgronecitefull** [comment]
You definitely deserve a coffee! I got this error mssg recently, that said, I am not seeing the actual error… Cheers  -- Kyle GroneCEO & Founder 602.544.6125 citefull.com      From: David WilliamesSent: Saturday, January 30, 2021 11:32 PMTo: DWilliames/google-sheets-sync-figmaCc: KGrone; MentionSubject: Re: [DWilliames/google-sheets-sync-figma] Error: in set_y: Expected "y" to have type number but got NaN instead (#7) Thanks @kgronecitefull — that's amazing to hear how valuable it is :)If you want to support the development of it (no pressure at all); I just set up a page at: buymeacoffee.com/davew where you could shout me a coffee.Every little bit is super appreciated 🙌—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
