### ISSUE TITLE
Fetching Data from google Sheet not working

### ISSUE THREAD

**Issue by jcneuron** [DWilliames/google-sheets-sync-figma#93]
**Describe the bug**
I am trying to fetch data from a google sheet that meets all the criteria to successfully display the data from Google Sheet unto Figma. It gets stuck at fetching data (see jpg).

**To Reproduce**
Steps to reproduce the behavior: (include a screen recording if possible) and link to Figma file and Google Sheet file

**Original** Working Version:
-Google Sheet:
https://docs.google.com/spreadsheets/d/1G2GqRjKXeYu6UjIDzJ6IA4mfkqBS5r2AbQMB0WXNVIY/edit?usp=sharing
-Figma File
https://www.figma.com/file/jUmR8RjEq8nhBfBr1t6cZB/Novy-Menu?node-id=0%3A1

**Copy** but not working (different google sheet, different Figma file, same settings and content)
-Google Sheet:
https://docs.google.com/spreadsheets/d/1IfCwotDrC7wDLl9FxiPXISefgMe16lMl/edit?usp=sharing&ouid=109364941918473481677&rtpof=true&sd=true
-Figma File
https://www.figma.com/file/rvMRRsP2DKiEqelp7t7c4M/Novy-Menu-(Copy)?node-id=0%3A1

**Expected behavior**
Copy should work exactly as original

**Additional context**

![google sheet sync not fetching](https://user-images.githubusercontent.com/28060487/155112990-6e5dbeb1-21fb-4499-80c5-718ff482db43.jpg)
The menu near the Figma components is the main menu that displays the data

**Comment by Pokesh** [comment]
I've got the same problem.

**Comment by jcneuron** [comment]
> I've got the same problem.

Let me know if you find a solution, it was working fine back in November

**Comment by jcneuron** [comment]
> I've got the same problem.

if you click on the Google sheets copy you’ll see it say “.XLSX” at the top. You need to convert it to a Google sheet by clicking File > Save as Google Sheets. Then you can grab a new sharing link that if you click on the Google sheets copy you’ll see it say “.XLSX” at the top. You need to convert it to a Google sheet by clicking File > Save as Google Sheets. Then you can grab a new sharing link and it should work and it should work
